using regex to delete png files to make sure no uninteded pngs are deleted, working on allowing user to pick another working directory than ~. Still needs testing and further options

diff --git a/silentcast b/silentcast
--- a/silentcast
+++ b/silentcast
@@ -41,10 +41,20 @@ do
 done
 shift "$((OPTIND-1))" # get rid of everything just processed leaving anything else as $1 $2 etc.
 
-unset fps area_choice area ffcoms_running castnum rate arg_form silentcast_dir doc_dir
+unset fps area_choice area ffcoms_running castnum rate arg_form silentcast_dir doc_dir working_dir tmp
+
+ffcoms_running=`pgrep -f ffcom | wc -l`
+if (($ffcoms_running > 1))
+then
+	echo "You are already doing a recording of a recording. Further nesting of silentcasts is not supported." \
+	| yad --text-info --wrap --on-top --center --window-icon="$doc_dir/record.png" --title="Error" --text="<b>SILENTCAST ? </b>"
+	exit -1
+else
+	let castnum=$ffcoms_running+1
+fi
+
 #defaults
 fps=8
-ffcoms_running=0
 area_choice="Fullscreen"
 area="f"
 doc_dir=/usr/share/doc/silentcast
@@ -53,23 +63,8 @@ then
 	doc_dir="$( cd "$(dirname "$0")" ; pwd -P )"
 fi
 
-ffcoms_running=`pgrep -f ffcom | wc -l`
-if (($ffcoms_running > 0))
-then
-	if (($ffcoms_running > 1))
-	then
-		echo "You are already doing a recording of a recording. Further nesting of silentcasts is not supported."
-		exit -1
-	else
-		mkdir -p ~/silentcast/silentcast
-		castnum=2
-		silentcast_dir=~/silentcast/silentcast
-	fi
-else
-	mkdir -p ~/silentcast 
-	silentcast_dir=~/silentcast
-	castnum=1
-fi
+working_dir=~
+df /tmp | grep -q tmpfs && tmp=/tmp || tmp=/dev/shm # offer /tmp if it's shared memory disk, otherwise /dev/shm (debian & ubuntu)
 
 arg_form=`yad --form --on-top --center\
 	--title="Silentcast v$v" \
@@ -80,23 +75,47 @@ arg_form=`yad --form --on-top --center\
   <span background="white">  click <a href="https://github.com/colinkeenan/silentcast/#silentcast">web README.md</a> or install a web  </span>\n\
   <span background="white">  browser addon for markdown and click  </span>\n\
   <span background="white">  <a href="file://'$doc_dir'/README.md">local README.md</a>                       </span>\n\
-  <span background="white">                                        </span></tt>'\
+  <span background="white">                                        </span></tt>\n\
+  \n\
+ In the Working Directory specified below, silentcast \n\
+ or silencast/silentcast will be created to contain \n\
+ temp.mkv and anim.gif: Choose one or type it in.'\
   	--separator="," \
+	--field="Working Directory":CBE \
 	--field="Area to be recorded":CB \
 	--field="Frames per second" \
+	"$HOME"!"$tmp"!"other" \
 	"Fullscreen"!"Transparent Window Interior"!"Interior of a Window"!"Entirety of a Window" 8`
 (($? != 0)) && exit 1 #Cancel was clicked
 
-area_choice="$(awk -F, '{print $1}' <<<"$arg_form")"
-fps="$(awk -F, '{print $2}' <<<"$arg_form")"         # getting second field this way only works when --separator="'"
+working_dir="$(awk -F, '{print $1}' <<<"$arg_form")"         
+if ! [ -d "$working_dir" ]
+then
+	echo "$working_dir is not an existing Directory, so the Silentcast directory can't be created there" \
+	| yad --text-info --wrap --on-top --center --window-icon="$doc_dir/record.png" --title="Error" --text="<b>SILENTCAST ? </b>"
+	exit -1
+fi
+
+area_choice="$(awk -F, '{print $2}' <<<"$arg_form")" # getting 2nd & 3rd fields this way only works when --separator=","
+fps="$(awk -F, '{print $3}' <<<"$arg_form")"         
 
 area=${area_choice,} # lower case first letter
 area=${area:0:1}     # area is now one of f t i e
+
+if (($castnum == 2))
+then 
+	mkdir -p $working_dir/silentcast/silentcast
+	silentcast_dir=$working_dir/silentcast/silentcast
+else
+	mkdir -p $working_dir/silentcast 
+	silentcast_dir=$working_dir/silentcast
+	castnum=1
+fi
 
 source genffcom "-a"$area "-r"$fps "-d"$silentcast_dir $castnum 
 (($? != 0)) && exit 1 #Cancel was clicked
 bash $silentcast_dir/ffcom
 (($? != 0)) && exit 1 #Cancel was clicked
-source temptoanim $castnum $fps
+source temptoanim $castnum $fps $working_dir
 
 # End of file
diff --git a/temptoanim b/temptoanim
--- a/temptoanim
+++ b/temptoanim
@@ -1,25 +1,33 @@
 #!/bin/bash
 # $1 is silentcast# (i.e. castnum)
 # $2 is fps
+# $3 is working directory (working_dir) and is optional - defaults to ./
 
 # Usage info
 show_help() {
 cat << EOF
 temptoanim converts temp.mkv to anim.gif
 
-Usage: temptoanim silentcast# fps
+Usage: temptoanim silentcast# fps [working_dir]
 
-    silentcast# must be 0, 1, or 2
+    silentcast#     must be 0, 1, or 2
 
-	0: tries to convert ./temp.mkv
-	1: tries to convert ~/silentcast/temp.mkv
-	2: tries to convert ~/silentcast/silentcast/temp.mkv
+	0: tries to convert ./temp.mkv (if working_dir is also 
+	   specified, it will be ignored)
+	1: tries to convert working_dir/silentcast/temp.mkv
+	2: tries to convert working_dir/silentcast/silentcast/temp.mkv
 
-    fps is an integer and must match the frames per second used to
-        create temp.mkv. temptoanim doesn't verify the actual fps 
-	in temp.mkv.
+    fps             is an integer and must match the frames per second used to
+	            create temp.mkv. temptoanim doesn't verify the actual fps 
+	            in temp.mkv.
 	
-    Both args are required.
+    Both silentcast# and fps are required and must appear in the correct
+    order.
+
+    working_dir     must be the last arg, defaults to ~/ and is where 
+                    temptoanim will expect to find the silentcast or 
+		    silentcast/silentcast directory
+
 
 There are some dialogues that come up, and it's important to read
 and understand them. View /usr/share/doc/silentcast/README.md with
@@ -33,30 +41,45 @@ then
 	show_help
 	exit 0
 fi
+
 castnum=""
 if (($1 != 0))
 then 
 	castnum=$1
 fi
+
 cut=0
 total_cut=0
 group=0
 count=0
 
-if (($1 == 1)); then cd ~/silentcast
-elif (($1 == 2)); then cd ~/silentcast/silentcast
+if [ "$3" != "" ] 
+then
+	working_dir=$3
+else
+	working_dir=.
+fi
+
+if ! [ -d $working_dir/ ]
+then
+	echo "$working_dir is not an existing directory, so the silentcast directory can't be there" \
+	| yad --text-info --wrap --on-top --center --window-icon="$doc_dir/record.png" --title="Error" --text="<b>SILENTCAST ? </b>"
+	exit -1
+fi
+if (($1 == 1)); then cd $working_dir/silentcast
+elif (($1 == 2)); then cd $working_dir/silentcast/silentcast
 fi
 
 if ! [ -f temp.mkv ]
 then
 	echo "temp.mkv not found, so can't convert it to anim.gif" \
 	| yad --text-info --wrap --on-top --center --window-icon="$doc_dir/record$castnum".png --title="Error" --text="<b>SILENTCAST $1 </b>"
-	exit 0
+	exit -1
 fi
 
 xdg-open ./
 find -maxdepth 1 -name 'anim.gif' -delete
-find -maxdepth 1 -name 'ew*png' -delete
+find -maxdepth 1 -regex '\.\/ew-[0-9][0-9][0-9]\.png' -delete
 
 ffmpeg -i temp.mkv -r $2 -an ew-%03d.png \
 	| yad --progress --on-top --center --window-icon="$doc_dir/record$castnum".png --text="<b>SILENTCAST $1 </b> \n\
