still working on temptoanim dialogues. also put in a check for temp.mkv with error/exit

diff --git a/temptoanim b/temptoanim
--- a/temptoanim
+++ b/temptoanim
@@ -39,6 +39,13 @@ unset cut group count
 if [ "$1" -eq 1 ]; then cd ~/silentcast
 elif [ "$1" -eq 2 ]; then cd ~/silentcast/silentcast
 fi
+if ! [ -f temp.mkv ]
+then
+	echo "temp.mkv not found, so can't convert it to anim.gif" \
+	| yad --text-info --on-top --center --window-icon="media-record" --title="Error" --text="<b>SILENTCAST $1 </b>"
+	exit 0
+fi
+
 xdg-open ./
 if [ -f anim.gif ]; then rm anim.gif
 fi
@@ -46,13 +53,13 @@ if ls *png &> /dev/null; then rm *png
 fi
 
 ffmpeg -i temp.mkv -r $2 -an ew-%03d.png \
-	| yad --progress --on-top --window-icon="media-record" --text="<b>SILENTCAST $1 </b> \n\
+	| yad --progress --on-top --center --window-icon="media-record" --text="<b>SILENTCAST $1 </b> \n\
 Creating images from temp.mkv" --pulsate --auto-close
 [ "$?" -ne "0" ] && exit 1 #Cancel was clicked
 
 while ! [ -f anim.gif ]
 do
-    cut=`yad --entry --on-top --window-icon="media-record"\
+    cut=`yad --entry --on-top --center --window-icon="media-record"\
         --title="Prepare images before converting to Anim.gif" \
         --text="<b>SILENTCAST $1 </b> \n\
 Manually delete or otherwise manipulate the images and click OK,\n\
@@ -79,13 +86,13 @@ Enter any positive integer less than the total number of images. It works like t
     	done
     fi
     convert -adjoin -delay "$cut"x"$2" -layers optimize *png anim.gif | \
-	    yad --progress --on-top --title="convert" --window-icon="media-record" --text="<b>SILENTCAST $1 </b> \n\
+	    yad --progress --on-top --center --title="convert" --window-icon="media-record" --text="<b>SILENTCAST $1 </b> \n\
 Replacing images with anim.gif..." --pulsate --auto-close
 [ "$?" -ne "0" ] && exit 1 #Cancel was clicked
     if ! [ -f anim.gif ]
     then 
-    	  yad --error --on-top --window-icon="media-record" --title="error" --text="<b>SILENTCAST $1 </b> \n\
-Too many images for the available memory - convert crashed. Try closing other applications, creating a swap file, or removing unecessary images."
+	echo "Too many images for the available memory - convert crashed. Try closing other applications, creating a swap file, or removing unecessary images." |\
+    	  yad --text-info --on-top --center --window-icon="media-record" --title="Error" --text="<b>SILENTCAST $1 </b>"
 [ "$?" -ne "0" ] && exit 1 #Cancel was clicked
     else
     	  rm *png
